// This File has been authored by AllTheMods Staff, or a Community contributor for use in AllTheMods - AllTheMods 9.
// As all AllTheMods packs are licensed under All Rights Reserved, this file is not allowed to be used in any public packs not released by the AllTheMods Team, without explicit permission.

const $SoundEvents = Java.loadClass("net.minecraft.sounds.SoundEvents")
const $SoundSource = Java.loadClass("net.minecraft.sounds.SoundSource")
const $ExistingSoundEntry = Java.loadClass("com.gregtechceu.gtceu.api.sound.ExistingSoundEntry")

GTCEuStartupEvents.registry('gtceu:recipe_type', allthemods => {
    allthemods.create('ore_processing_plant')
        .category('ore_processing_plant')
        .setEUIO('in')
        .setMaxIOSize(1, 9, 2, 0)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MACERATOR);
    allthemods.create('ore_bathing_plant')
        .category('ore_processing_plant')
        .setEUIO('in')
        .setMaxIOSize(1, 9, 2, 0)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.BATH);
    allthemods.create('ore_sifting_plant')
        .category('ore_processing_plant')
        .setEUIO('in')
        .setMaxIOSize(1, 9, 2, 0)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(new $ExistingSoundEntry($SoundEvents.SAND_PLACE, $SoundSource.BLOCKS));
})

GTCEuStartupEvents.registry('gtceu:machine', allthemods => {
    allthemods.create('ore_processing_plant', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeTypes([GTRecipeTypes.get('ore_processing_plant'), GTRecipeTypes.get('ore_bathing_plant'), GTRecipeTypes.get('ore_sifting_plant')])
        .appearanceBlock(GCYMBlocks.CASING_SECURE_MACERATION)
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_NON_PERFECT_SUBTICK])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("      BBBBBBB      ", "       B   B       ", "       B   B       ", "       B   B       ", "       BBBBB       ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ")
            .aisle("      BBBBBBB      ", "       BCBCB       ", "       BCBCB       ", "       BCBCB       ", "      BBBBBBB      ", "         B         ", "         B         ", "         B         ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ")
            .aisle("      BBBBBBB      ", "    D DBEEEBD D    ", "       BEEEB       ", "    D DBEEEBD D    ", "      BB   BB      ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "                   ", "                   ", "                   ", "                   ")
            .aisle("   BBBBBBBBBBBBB   ", "    DFD EEE DFD    ", "     F  EEE  F     ", "    DFD EEE DFD    ", "     DBB   BBD     ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       BBBBB       ", "                   ", "                   ", "                   ")
            .aisle("   BBBBBBBBBBBBB   ", "  DDD DDEEEDD DDD  ", "    D D EEE D D    ", "  DDD DDEEEDD DDD  ", "    DDDB   BDDD    ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       BBBBB       ", "                   ", "                   ", "                   ")
            .aisle("   BBBBBBBBBBBBB   ", "   F G       G F   ", "   F G       G F   ", "   F G       G F   ", "   DDGDHHHHHDGDD   ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "                   ", "                   ", "                   ", "                   ")
            .aisle("BBBBBBBBBBBBBBBBBBB", "  DDD DDD DDD DDD  ", "    D D     D D    ", "  DDD DDD DDD DDD  ", " BBBDDD     DDDBBB ", "     H       H     ", "     H       H     ", "     H       H     ", "     H       H     ", "     H       H     ", "     H       H     ", "     HHH C HHH     ", "       HH HH       ", "                   ", "                   ", "                   ")
            .aisle("BBBBBBBBBBBBBBBBBBB", "BBB D D     D D BBB", "BBB             BBB", "BBB D D     D D BBB", "BBBBBH       HBBBBB", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH  D D  HBB   ", "   BBHH DCD HHBB   ", "   BB H DDD H BB   ", "       DDDDD       ", "        DDD        ", "         D         ")
            .aisle("BBBBBBBBBBBBBBBBBBB", " CEEE D III D EEEC ", " CEEE   III   EEEC ", " CEEE D III D EEEC ", "BB   H  III  H   BB", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H DIIID H  C  ", "  C  H DIIID H  C  ", "   BB HDIIIDH BB   ", "       DIIID       ", "       DIIID       ", "        III        ")
            .aisle("BBBBBBBBBBBBBBBBBBB", " BEEE   IJI   EEEB ", " BEEE   IJI   EEEB ", " BEEE   IJI   EEEB ", "BB   H  IJI  H   BB", " BC  C  IJI  C  CB ", " BC  C  IJI  C  CB ", " BC  C  IJI  C  CB ", "  C  C  IJI  C  C  ", "  C  C  IJI  C  C  ", "  C  C  IJI  C  C  ", "  C  CCCIJICCC  C  ", "   BB  DIJID  BB   ", "       DIJID       ", "       DIJID       ", "       DIKID       ")
            .aisle("BBBBBBBBBBBBBBBBBBB", " CEEE D III D EEEC ", " CEEE   III   EEEC ", " CEEE D III D EEEC ", "BB   H  III  H   BB", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H  III  H  C  ", "  C  H DIIID H  C  ", "  C  H DIIID H  C  ", "   BB HDIIIDH BB   ", "       DIIID       ", "       DIIID       ", "        III        ")
            .aisle("BBBBBBBBBBBBBBBBBBB", "BBB D D     D D BBB", "BBB             BBB", "BBB D D     D D BBB", "BBBBBH       HBBBBB", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH       HBB   ", "   BBH  D D  HBB   ", "   BBHH DCD HHBB   ", "   BB H DDD H BB   ", "       DDDDD       ", "        DDD        ", "         D         ")
            .aisle("BBBBBBBBBBBBBBBBBBB", "  DDD DDD DDD DDD  ", "    D D     D D    ", "  DDD DDD DDD DDD  ", " BBBDDD     DDDBBB ", "     H       H     ", "     H       H     ", "     H       H     ", "     H       H     ", "     H       H     ", "     H       H     ", "     HHH C HHH     ", "       HH HH       ", "                   ", "                   ", "                   ")
            .aisle("   BBBBBBBBBBBBB   ", "   F G       G F   ", "   F G       G F   ", "   F G       G F   ", "   DDGDHHHHHDGDD   ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "     HHHHCHHHH     ", "                   ", "                   ", "                   ", "                   ")
            .aisle("   BBBBBBBBBBBBB   ", "  DDD DDEEEDD DDD  ", "    D D EEE D D    ", "  DDD DDEEEDD DDD  ", "    DDDB   BDDD    ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       BBBBB       ", "                   ", "                   ", "                   ")
            .aisle("   BBBBBBBBBBBBB   ", "    DFD EEE DFD    ", "     F  EEE  F     ", "    DFD EEE DFD    ", "     DBB   BBD     ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       B   B       ", "       BBBBB       ", "                   ", "                   ", "                   ")
            .aisle("      BBBBBBB      ", "    D DBEEEBD D    ", "       BEEEB       ", "    D DBEEEBD D    ", "      BB   BB      ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "        CCC        ", "                   ", "                   ", "                   ", "                   ")
            .aisle("      BBBBBBB      ", "       BCBCB       ", "       BCBCB       ", "       BCBCB       ", "      BBBBBBB      ", "         B         ", "         B         ", "         B         ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ")
            .aisle("      BBBBBBB      ", "       BAAAB       ", "       BA~AB       ", "       BAAAB       ", "       BBBBB       ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ")
            .aisle("       AAAAA       ", "                   ", "                   ", "                   ", "       AAAAA       ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ", "                   ")
            .where("~", Predicates.controller(Predicates.blocks(definition.get())))
            .where("B", Predicates.blocks("gtceu:secure_maceration_casing"))
            .where("C", Predicates.blocks("gtceu:tempered_glass"))
            .where("F", Predicates.blocks("gtceu:assembly_line_grating"))
            .where("K", Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1))
            .where("D", Predicates.blocks("gtceu:vibration_safe_casing"))
            .where("H", Predicates.blocks("gtceu:watertight_casing"))
            .where("E", Predicates.blocks("gtceu:crushing_wheels"))
            .where("I", Predicates.blocks("gtceu:hssg_coil_block"))
            .where("J", Predicates.blocks("gtceu:titanium_pipe_casing"))
            .where("A", Predicates.blocks("gtceu:secure_maceration_casing")
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
                .or(Predicates.autoAbilities(definition.getRecipeTypes()))
            )
            .where("G", Predicates.blocks("gtceu:steel_pipe_casing"))
            .build()
        )
        .workableCasingModel('gtceu:block/casings/gcym/secure_maceration_casing', 'gtceu:block/multiblock/gcym/large_maceration_tower')
})

// This File has been authored by AllTheMods Staff, or a Community contributor for use in AllTheMods - AllTheMods 9.
// As all AllTheMods packs are licensed under All Rights Reserved, this file is not allowed to be used in any public packs not released by the AllTheMods Team, without explicit permission.